const Types = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    CLEAR_USER: 'CLEAR_USER',
    SAVELANG: "SAVELANG",
    CHECKLOGIN: "CHECKLOGIN",
    SAVEDATAUSER:"SAVEDATAUSER",
    NAVTOLOG: "NAVTOLOG",
  };

  export default Types;
